apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myfront-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header 'Access-Control-Allow-Origin' '*' always;
      add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
      add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, X-Frontend-Auth' always;
      add_header 'Access-Control-Expose-Headers' 'Content-Length' always;
      add_header 'Access-Control-Allow-Credentials' 'false' always;

      if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Max-Age' 86400;
        add_header 'Content-Type' 'text/plain; charset=utf-8';
        add_header 'Content-Length' 0;
        return 204;
      }
      
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: go-todo-app-backend-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: go-todo-app-frontend-service
            port:
              number: 80
