apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myfront-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-todo-app-frontend
                port:
                  number: 80